### ISSUE TITLE
PostfinanceTransaction cannot be received

### ISSUE THREAD

**Issue by schmijos** [simplificator/datatrans#7]
On successful PostFinance transactions the success path is called with the following parameter: `"responseMessage"=>"YellowPay transaction Ok"`

This is not accepted as _authorized_ here: https://github.com/simplificator/datatrans/blob/master/lib/datatrans/web/transaction/authorize.rb#L12

**Comment by pascalbetz** [comment]
Hello Josua

Thanks for the feedback. I'll need to investigate a bit because it's been a long time. Can you come up with a PR?

Pascal

**Comment by pascalbetz** [comment]
@agileapplications 
Since you are using the Gem in one of your projects: can you check/delegate (there are two open PR since quite a while as well)?

**Comment by TatianaPan** [comment]
Fixed in #39 and included in v4.0.1. Thank you very much @schmijos for your contribution!
